keras_file_path = "0_models/keras_models/model_1/generator_epoch_001000.keras"

model_split_into_files = "0_models/json_models/model_1"

path_to_keras_implementation_intermediary = "1_implementation_keras/intermediary"
path_to_non_keras_implementation_intermediary = "2_implementation_without_keras/intermediary"
path_to_c_implementation_intermediary = "3_implementation_c/intermediary"
path_to_cpp_implementation_intermediary = "4_implementation_cpp/intermediary"
path_to_rust_implementation_intermediary = "5_implementation_rust/main/intermediary"


## todo isolate random vector